BEGIN;

CREATE TABLE IF NOT EXISTS public.sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  job TEXT NOT NULL CHECK (job IN ('prices', 'daily_log', 'benchmarks')),
  status TEXT NOT NULL CHECK (status IN ('running', 'success', 'partial', 'failed')),
  trigger TEXT NOT NULL CHECK (trigger IN ('cron', 'manual')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  details JSONB NOT NULL DEFAULT '{}'::JSONB,
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS sync_runs_user_started_idx
  ON public.sync_runs (user_id, started_at DESC);

CREATE INDEX IF NOT EXISTS sync_runs_user_job_started_idx
  ON public.sync_runs (user_id, job, started_at DESC);

ALTER TABLE public.sync_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sync_runs_owner_select_policy ON public.sync_runs;
CREATE POLICY sync_runs_owner_select_policy
  ON public.sync_runs
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.sync_runs FROM anon, authenticated;
GRANT SELECT ON TABLE public.sync_runs TO authenticated;

COMMIT;
