CREATE TABLE IF NOT EXISTS public.portfolio_backups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('manual', 'automatic', 'pre_restore')),
  payload JSONB NOT NULL,
  byte_size INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS portfolio_backups_user_created_idx
  ON public.portfolio_backups (user_id, created_at DESC);

ALTER TABLE public.portfolio_backups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS portfolio_backups_owner_policy ON public.portfolio_backups;
CREATE POLICY portfolio_backups_owner_policy
  ON public.portfolio_backups
  FOR ALL
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.portfolio_backups FROM anon;
GRANT SELECT, INSERT, DELETE ON TABLE public.portfolio_backups TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.portfolio_backups_id_seq TO authenticated;
