CREATE TABLE IF NOT EXISTS public.rebalance_targets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('stocks', 'pension')),
  asset_id BIGINT NOT NULL,
  target_weight NUMERIC(7, 4) NOT NULL DEFAULT 0 CHECK (target_weight >= 0 AND target_weight <= 100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, category, asset_id)
);

CREATE INDEX IF NOT EXISTS rebalance_targets_user_category_idx
  ON public.rebalance_targets (user_id, category);

ALTER TABLE public.rebalance_targets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rebalance_targets_owner_policy ON public.rebalance_targets;
CREATE POLICY rebalance_targets_owner_policy
  ON public.rebalance_targets
  FOR ALL
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.rebalance_targets FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.rebalance_targets TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.rebalance_targets_id_seq TO authenticated;
