CREATE TABLE IF NOT EXISTS public.portfolio_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('stocks', 'pension')),
  account_name TEXT NOT NULL,
  detected_amount NUMERIC NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  event_type TEXT NOT NULL CHECK (
    event_type IN ('deposit', 'withdrawal', 'valuation_adjustment', 'ignored')
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, date, category, account_name)
);

ALTER TABLE public.portfolio_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS portfolio_events_owner_policy ON public.portfolio_events;
CREATE POLICY portfolio_events_owner_policy
  ON public.portfolio_events
  FOR ALL
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.portfolio_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.portfolio_events_id_seq TO authenticated;

CREATE INDEX IF NOT EXISTS portfolio_events_user_date_idx
  ON public.portfolio_events (user_id, date DESC);
